---
title: "Candy Power Ranking"
author: "Thomas Alcock"
date: "19 2 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(GGally)
library(plotly)
library(tibble)
library(tidyr)
library(gridExtra)
library(knitr)
library(forcats)
library(purrr)
```

## EDA

```{r prev}
candy_df <- read.csv(
  file = "candy-data.csv",
  header = TRUE
) %>% as_tibble()

candy_df %>% 
  arrange(desc(winpercent)) %>% 
  slice(1:10) %>% 
  select(competitorname, winpercent) %>% 
  knitr::kable()
```

```{r eda}
# no significat 
bi_plots <- ggpairs(candy_df %>% select_if(is.double))
ggplotly(bi_plots)
```

```{r eda2}
cdf_long <- pivot_longer(candy_df, cols = c(-competitorname, -sugarpercent, -winpercent, -pricepercent))

sc_plots <- function(df, cond_var, p_size = 3, opacity = 4){
  df <- df %>% 
    filter(name == cond_var) %>% 
    select(-name) %>% 
    mutate(value = ifelse(value==1, "Ja", "Nein")) %>% 
    rename(!!sym(cond_var) := value) %>% 
    mutate(!!sym(cond_var) := factor(!!sym(cond_var)))
  
  p1 <- ggplot(df, aes(x = pricepercent, y = winpercent, color = !!sym(cond_var))) +
    geom_point(size = p_size, alpha = 1/opacity) + theme_minimal() + 
    geom_smooth(method = "lm", se = FALSE, size=0.5)
  
  p2 <- ggplot(df, aes(x = sugarpercent, y = winpercent, color = !!sym(cond_var))) +
    geom_point(size = p_size, alpha = 1/opacity) + theme_minimal() +
    geom_smooth(method = "lm", se = FALSE, size=0.5)
  
  p3 <- grid.arrange(p1, p2)
}
```


## Boxplots

```{r}
cdf_long %>% 
  mutate(value = fct_reorder(paste0(value), winpercent),
         value = ifelse(value == 1, "Ja", "Nein")) %>% 
  ggplot(aes(x = value, y = winpercent, color = name)) + 
  geom_boxplot() +
  facet_wrap(.~name, ncol = 5) +
  theme_minimal() +
  labs(x = "Besitzt Eigenschaft", y = "Beliebtheit",  color = "")
```

Für ausgewählte Variablen mit großen Unterschieden werden Scatterplots erstellt.

```{r}
sc_plots(cdf_long, "chocolate")
sc_plots(cdf_long, "crispedricewafer")
sc_plots(cdf_long, "peanutyalmondy")
```

Für einige Features nur relativ geringe Anzahl an Ja Einträgen. deshalb Bootstrap Sampling mit Stratifizierung nach peanutyalmondy, weil diese Eigenschaft hohen Anteil an 

```{r}
candy_df %>% 
  select_if(is.integer) %>% 
  purrr::map_dfr(mean) %>% 
  pivot_longer(cols = everything()) %>% 
  arrange(value) %>%
  ggplot(aes(x = value, y = fct_reorder(name, value))) +
  geom_bar(stat = "identity") + theme_minimal() +
  labs(x = "Relativer Anteil", y = "Eigenschaft")
```

```{r lm}
library(glmnet)
library(tidymodels)
library(parsnip)
library(recipes)
library(tune)
library(rsample)
library(tune)
library(dials)
library(vip)
library(forcats)

boots <- bootstraps(candy_df, times = 1000, strata = "peanutyalmondy")

run_boot_model <- function(boot_split){
  
  df <- boot_split %>% analysis()
  simple_lm <- lm(winpercent ~ ., data = df %>% select(-competitorname))
  raw_summary <- simple_lm %>% summary()
  tidy_summary <- tidy(raw_summary)
  tidy_summary$adj_r_sq <- raw_summary$adj.r.squared
  tidy_summary$id <- boot_split$id$id
  tidy_summary
}

bs_res <- map_dfr(boots$splits, run_boot_model)

```

```{r}
plot_data <- bs_res %>% 
  filter(term != "(Intercept)")
  
bounds <- plot_data %>% 
  group_by(term) %>% 
  summarise(
    upper_bound = quantile(estimate, probs = 0.975),
    lower_bound = quantile(estimate, probs = 0.025)
  )

bs_plot <- plot_data %>% 
  select(term, estimate) %>% 
  pivot_longer(cols = estimate) %>% 
  ggplot(aes(x = value, fill = term, color = term)) + 
  geom_density(alpha = 0.7) + 
  facet_wrap(. ~ term, nrow = 4) +
  theme_minimal() + theme(legend.position = "none") +
  labs(x = "Regressionskoeffizient", y = "Dichte", title = "Koeffizienten nach Bootstrap Sampling") +
  geom_vline(data = bounds, mapping = aes(xintercept = upper_bound, color = term), linetype = 2) +
  geom_vline(data = bounds, mapping = aes(xintercept = lower_bound, color = term), linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2, alpha = 0.5)
```

```{r}


set.seed(1)

model_df <- candy_df %>% 
  mutate_if(is.integer, as.logical)

folds <- vfold_cv(model_df, v = 20)

lasso <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet") 

lasso_rec <- recipe(winpercent ~ ., data = model_df) %>% 
  update_role(competitorname, new_role = "ID") %>% 
  step_normalize(sugarpercent, pricepercent)

wf <- workflow() %>% 
  add_recipe(lasso_rec)
  
l_grid <- grid_regular(penalty(), levels = 50)

res <- tune_grid(
  wf %>% add_model(lasso), 
  resamples = folds, 
  grid = l_grid
)
  
tune_df <- res %>% 
  collect_metrics()

tune_plot <- tune_df %>% 
  filter(.metric == "rsq")
  ggplot(aes(x = penalty, y = mean, color = .metric)) +
  geom_errorbar(
    aes(ymin = mean - std_err,
        ymax = mean + std_err),
    alpha = 0.5
  ) +
  geom_line(aes(y = mean)) +
  theme_minimal() +
  scale_x_log10()

tune_plot

best_model <- res %>% 
  select_best("rsq")

final_model <- finalize_workflow(
  wf %>% add_model(lasso),
  best_model
)


final_model %>% 
  fit(data = model_df) %>% 
  pull_workflow_fit() %>% 
  vi(lambda = best_model$penalty) %>% 
  mutate(Sign = if_else(Sign == "NEG", "Negativer Effekt", "Positiver Effekt")) %>% 
  ggplot(aes(x = Importance, y = fct_reorder(Variable, Importance), fill = Sign)) +
  geom_bar(stat = "identity") +
  theme_minimal() + labs(
    x = "Relevanz", y = "Eigenschaft", fill = "",
    title = "Relevanz von Eigenschaften für Beliebtheit"
  )

```

```{r insample_preds}

pred_model <- final_model %>% 
  fit(data = model_df)

pred_data <- pred_model %>% 
  predict(model_df) %>% 
  bind_cols(model_df)

insample_preds <- pred_data %>% 
  ggplot(aes(x = winpercent, y = .pred)) +
  geom_point(size = 3, alpha = 0.5) + theme_minimal() +
  labs(x="Beobachtet", y="Predicted")



```

